FROM python:3.11-slim
WORKDIR /app
COPY requirements/requirements_ui.txt .
RUN pip install --no-cache-dir -r requirements_ui.txt
COPY ui ./ui
CMD ["streamlit", "run", "ui/app.py", "--server.address=0.0.0.0", "--server.port=8501"]