FROM python:3.11-slim
WORKDIR /app
COPY requirements/requirements_sink.txt .
RUN pip install --no-cache-dir -r requirements_sink.txt
COPY services/sink ./services/sink
ENV PYTHONPATH="/app"
CMD ["python", "services/sink/main.py"]