name: hw4_dbt
version: 1.0.0
config-version: 2

profile: hw4_dbt

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
docs-paths: ["docs"]
asset-paths: []

dispatch:
  - macro_namespace: dbt
    search_order: ["dbt_utils", "dbt"]

vars:
  transaction_amount_threshold_high: 500
  transaction_amount_threshold_medium: 200

models:
  hw4_dbt:
    +materialized: view
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
seeds:
  hw4_dbt:
    transactions:
      +column_types:
        transaction_time: DateTime
        merch: String
        cat_id: String
        amount: Float64
        name_1: String
        name_2: String
        gender: String
        street: String
        one_city: String
        us_state: String
        post_code: String
        lat: Float64
        lon: Float64
        population_city: UInt32
        jobs: String
        merchant_lat: Float64
        merchant_lon: Float64
